import { addIcons } from '@siemens/ix-icons';
import {
  iconAssetNetwork,
  iconAuditReport,
  iconChartDiagram,
  iconCheck,
  iconCloudUpload,
  iconClose,
  iconCode,
  iconDatabase,
  iconDocumentCode,
  iconDocumentInfo,
  iconDocumentReference,
  iconDownload,
  iconEye,
  iconFactoryReset,
  iconGauge,
  iconGraph,
  iconHome,
  iconInfo,
  iconListGraphics,
  iconMinus,
  iconNetworkDevice,
  iconPlay,
  iconProcessControl,
  iconProjectSettings,
  iconRefresh,
  iconRefreshSettings,
  iconSearch,
  iconShieldCheck,
  iconTagEye,
  iconUpload,
  iconWarning,
} from '@siemens/ix-icons/icons';

// iX icon exports are SVG data, not values accepted by <ix-icon name>. Register
// the small icon set used by the app once, then use their normalized names.
addIcons({
  iconAssetNetwork,
  iconAuditReport,
  iconChartDiagram,
  iconCheck,
  iconCloudUpload,
  iconClose,
  iconCode,
  iconDatabase,
  iconDocumentCode,
  iconDocumentInfo,
  iconDocumentReference,
  iconDownload,
  iconEye,
  iconFactoryReset,
  iconGauge,
  iconGraph,
  iconHome,
  iconInfo,
  iconListGraphics,
  iconMinus,
  iconNetworkDevice,
  iconPlay,
  iconProcessControl,
  iconProjectSettings,
  iconRefresh,
  iconRefreshSettings,
  iconSearch,
  iconShieldCheck,
  iconTagEye,
  iconUpload,
  iconWarning,
});

export const ixIconName = {
  assetNetwork: 'asset-network',
  auditReport: 'audit-report',
  chartDiagram: 'chart-diagram',
  check: 'check',
  cloudUpload: 'cloud-upload',
  close: 'close',
  code: 'code',
  database: 'database',
  documentCode: 'document-code',
  documentInfo: 'document-info',
  documentReference: 'document-reference',
  download: 'download',
  eye: 'eye',
  factoryReset: 'factory-reset',
  gauge: 'gauge',
  graph: 'graph',
  home: 'home',
  info: 'info',
  listGraphics: 'list-graphics',
  minus: 'minus',
  networkDevice: 'network-device',
  play: 'play',
  processControl: 'process-control',
  projectSettings: 'project-settings',
  refresh: 'refresh',
  refreshSettings: 'refresh-settings',
  search: 'search',
  shieldCheck: 'shield-check',
  tagEye: 'tag-eye',
  upload: 'upload',
  warning: 'warning',
};
